---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - devops.pixocial.io
  resources:
  - testmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.pixocial.io
  resources:
  - testmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - devops.pixocial.io
  resources:
  - testmonitors/status
  verbs:
  - get
  - patch
  - update
