# permissions for end users to view testmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: testcrd
    app.kubernetes.io/managed-by: kustomize
  name: testmonitor-viewer-role
rules:
- apiGroups:
  - devops.pixocial.io
  resources:
  - testmonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.pixocial.io
  resources:
  - testmonitors/status
  verbs:
  - get
